INSERT INTO tbartigo (subTitulo1,p1,fkPublicacao) VALUES 
(
'Descobrimos o que está dentro da mala no Pulp Fiction',
'Finalmente. Depois de anos passados e das mais variadas teorias possíveis, descobrimos o que estava dentro da mala no filme Pulp Fiction. Era este objecto que Jules e Vincent mais queriam recuperar para devolverem ao seu patrão. A resposta do que lá se esconde é muito mais complexa do que estávamos à espera, ou então muito mais simples. As conspirações eram várias, desde as mais óbvias (a alma de Marcellus Wallace, o que justifica aquele adesivo na sua cabeça rapada), até ao mais louco e sonhador (como a ideia que sobrevivia nos anos 90 de que era um fato dourado que Elvis tinha usado). Só agora descobrimos a resolução deste mistério que há muito assolava estudantes e entusiastas de cinema. (o adesivo que lançou a teoria que seria a alma de Marcellus Wallace dentro da pasta) É aqui que entra o actor Phil LaMarr, que interpreta a icónica personagem de Marvin (Yes…), um dos membros do gang que rouba a pasta e que acaba por ser morto por Vince e Jules, só para ter de ser limpo pelo personagem incrível de Winston Wolf – interpretado por Harvey Keitel. Durante uma entrevista para o podcast “I Was There Too“, o actor contou finalmente o que estava dentro da mala.',
'Uma lâmpada. Uma lâmpada amarela de baixa voltagem.',
'É esta a resposta básica que responde a um dos grandes mistérios dos apreciadores de Tarantino, mas não poderia ficar por aqui. LaMarr perguntou a Tarantino, ainda durante as gravações, o que é suposto pensar que está dentro da mala. E Tarantino foi claro: “Está aquilo que tu quiseres que esteja.” Filósofico? Claro que sim. E foi por isso que o actor passou anos a pensar nesta resposta e nas suas possíveis leituras. “Se o Vincent a abrir e lá dentro estiver o que ele quiser ver, é uma pasta mágica. Mas se o conceito é que o que está dentro da mala é o bem mais desejado de cada um, isso é o que a audiência, ou melhor, quem vê, deseja.” ',
'1005'
);

INSERT INTO tbartigo (subTitulo1,p1,subTitulo2,p2,fkPublicacao) VALUES 
(
'“À espera de um milagre”, a verdadeira história por trás do filme',
'O Adolescente George Stinney Jr. de ascendência africana foi a pessoa mais jovem condenada à morte no século 20 nos Estados Unidos.Ele tinha apenas 14 anos quando foi executado em uma cadeira elétrica. Durante o julgamento, até o dia de sua execução, ele sempre carregava uma Bíblia nas mãos, alegando inocência. Ele foi acusado de matar duas meninas Brancas, Betty de 11 anos e Mary de 7, os corpos foram encontrados perto da casa onde o adolescente residia com seus pais. Naquela época, todos os jurados eram Brancos. O julgamento durou apenas 2 horas e a sentença foi dada 10 minutos depois. Os pais da criança foram ameaçados e impedidos de lhe dar presentes no tribunal e depois expulsos daquela cidade. Antes da execução, George passou 81 dias sem poder ver seus pais. Ele estava preso em uma cela solitária, a 80 km de sua cidade. Ele foi ouvido sozinho sem a presença de seus pais ou um advogado. Ele foi eletrocutado com 5.380 volts na cabeça.',
'Ele foi eletrocutado com 5.380 volts na cabeça.',
'70 anos depois, sua inocência foi finalmente comprovada por um juiz da Carolina do Sul. A criança era inocente, alguém fez de tudo para culpá-lo apenas por ser negro. Stephen King se inspirou neste caso para fazer seu livro “The Green Mile”, que foi levado ao cinema com a performance de Tom Hanks e Michael Clark Duncan interpretando John Coffey. Nome do Filme: “A Espera de um Milagre”',
'1006'
);

INSERT INTO tbartigo (subTitulo1,p1,subTitulo2,p2,fkPublicacao) VALUES 
(
'Princesa Mononoke E O Olhar Sobre O Ambientalismo',
'Que Hayao Miyazaki é responsável por alguns dos melhores filmes de animação (tanto do ocidente quanto do oriente) não é nenhuma novidade. Obras repletas de detalhes e com alto teor filosófico são algumas de suas marcas e em Princesa Mononoke (1997) elas se mantêm presentes, mas enquanto nos demais filmes a mensagem principal é de teor subjetivo, a desse clássico é bem mais objetiva: a importância do ambientalismo. O enredo do filme se passa no Japão medieval – sendo um pouco mais específico, no Período Muromachi – e tem como protagonista o Príncipe Ashitaka, que após entrar em um confronto com um demônio-javali para salvar seu vilarejo, acabou sofrendo graves consequências: um dano físico em seu braço e a expulsão de sua aldeia. Devido a isso, o herói parte em busca de uma cura para seu braço e de respostas do motivo daquele demônio ter atacado seu domínio – seu povo vivia em paz com a natureza até então -. Conforme a história progride, vamos conhecendo os demais personagens principais: San (a Princesa Mononoke) e Lady Eboshi.',
'Voltando para o filme',
'O nosso protagonista, o príncipe Ashitaka, não está nos extremos, pois vem de uma vila que vivia em comunhão com o meio ambiente. Porém, sua vila sobrevivia da agricultura e do artesanato, um quadro bem diferente daquele encontrado na Ilha de Ferro, mas mesmo assim o príncipe não desiste da sua ideia de uma convivência pacífica entre humanos e natureza. O desejo de Ashitaka pode ser comparado ao desenvolvimento sustentável, que é basicamente a utilização de recursos naturais de forma consciente para não afetar as próximas gerações. Observa-se ao final do filme que o desejo de Ashitaka foi alcançado e os habitantes da floresta e da Ilha de Ferro começaram a coexistir em paz, mas não são dados muitos detalhes de como o acordo foi realmente firmado. Ainda comparando com a realidade brasileira, devido a importância ecológica da área como já foi explicitado, o mais provável que acontecesse para permitir as atividades econômicas dentro da área, seria a criação do segundo tipo de Unidades de Conservação: as de Uso Sustentável. Elas estão previstas na Lei n° 9.985/00, artigo 7°, parágrafo 2°: “O objetivo básico das Unidades de Uso Sustentável é.',
'1007'
);

INSERT INTO tbartigo (subTitulo1,p1,subTitulo2,p2,fkPublicacao) VALUES 
(
'Merlin enganou a Divindade Suprema e o Rei Demônio',
'Frequentemente sou abordada por pessoas que dizem ter tentado acompanhar um anime da atualidade, mas que acabaram desistindo com o pretexto de que a história não prendia a atenção. Foi pensando nessas pessoas que decidi fazer essa resenha. Nanatsu no Taizai (Os Sete Pecados Capitais) foi lançado em Outubro de 2014 e conta a história de um grupo de guerreiros que viviam na região conhecida como Britânia. Após surgirem boatos de que haviam conspirado para derrubar o Reino Liones, esses guerreiros se separaram e desde então ninguém sabe o que aconteceu com eles. Após 10 anos, os Cavaleiros Sagrados do Reino Liones se juntaram para destronar o seu atual rei, bem como para assumirem o poder. Uma das princesas do reino, Elizabeth, consegue fugir e segue em busca dos Nanatsu no Taizai, na esperança de que eles possam ajudar a tirar os Cavaleiros Sagrados do poder. Nessa jornada, Elizabeth acaba indo parar em um bar onde conhece seu proprietário bastante atrevido e o seu porco de estimação.',
'Indicação certa e garantia de diversão',
'E novamente – para minha alegria – pude desfrutar de um anime em que as mulheres são caracterizadas como fortes guerreiras e não são poupadas de batalhas arriscadas (que isso se multiplique cada vez mais, daqui pra frente). Diane é uma gigante com uma força enorme e resistência maior ainda. Até mesmo a própria Elizabeth, que lamenta muitas vezes no decorrer da animação por não poder ajudar seus amigos a lutarem pelo fato de não possuir poderes como os deles, acaba mostrando sua verdadeira força no momento oportuno.',
'1008'
);

INSERT INTO tbartigo (subTitulo1,p1,subTitulo2,p2,fkPublicacao) VALUES 
(
'Onde estava Michael Scofield?',
'Ao escapar de Ogydia, prisão do Oriente Médio dominada pelo Estado Islâmico, o engenheiro revela ao irmão, Lincoln (Dominic Purcell), toda a verdade sobre sua morte forjada. Há sete anos, ele teria feito um acordo com um agente da CIA (Central de Inteligência Americana), chamado Poseidon, que o forçava a tirar vários terroristas de cadeias pelo mundo. Em troca, ele e Sara seriam absolvidos, já que Paul Kellerman (Paul Adelstein) nunca teria conseguido absolver os fugitivos de Fox River. No entanto, Scofield nunca mais poderia ver a família, que já estava ameaçada pelo agente, caso a proposta fosse recusada. Assim, para a proteção de todos, Scofield seguiu o plano.',
'Teoria: Jacob estaria ligado a Poseidon',
'Uma forte evidência que reforça a explicação de Scofield tem a ver com o atual marido de Sara, Jacob (Mark Feurestein). Ele trabalha para uma companhia chamada Poseidon, mesmo nome do agente que chantageou o engenheiro, e muitos espectadores acreditam que ele próprio seja o autor da enrascada. Em Ogydia, Scofield teve que assumir a identidade do terrorista Kaniel Outis, para poder ajudar outros criminosos a escapar de lá. No entanto, ele passou quatro anos na solitária, provavelmente por desobedecer alguma ordem de Poseidon. Se Jacob tiver ligação com a CIA, ele teria sido enviado para casar com Sara, a fim de mantê-la por perto como "garantia" do trabalho de Scofield. Além de sempre sabotar o passado do engenheiro, alegando que Michael sempre foi um criminoso, os agentes que invadem a casa da família e atiram na perna de Jacob seriam apenas parte do disfarce, para Sara acreditar que corre perigo.',
'1009'
);