INSERT INTO tbartigo (subTitulo1,p1,subTitulo2,p2,fkPublicacao) VALUES 
(
'Verdades nunca ditas sobre Hunter x Hunter',
'No mundo de Hunter x Hunter, de Yoshihiro Togashi, o ofício mais procurado é… bem, você provavelmente pode adivinhar pelo título. Esses “Hunters” podem viajar pelo mundo, derrotando e prendendo os vilões mais perigosos, procurando tesouros esquecidos e, no caso de Gon Freecss, que iniciou sua carreira como Hunter em 1998, talvez encontre seu pai e faça alguns amigos pelo caminho. Desde sua estreia, Hunter x Hunter se tornou incrivelmente popular em todo o mundo, tanto em anime quanto em mangá.',
'Veremos o Final de HxH?',
'Muito parecido com George R. R. Martin e Sua Canção do Gelo e Fogo, os hiatos prolongados de Hunter x Hunter fizeram com que alguns dos fãs mais extremos se preocupassem com o fato de nunca verem o fim da história, porque Togashi morreria antes de completá-la.. Esse clamor dos fãs do HxH (ou Hunter x Hunter x Hunters) parece ter sido tão sonoro que Togashi se sentiu compelido a responder em uma entrevista semanal do Shonen Jump. “Eu preciso terminar de escrever Hunter X Hunter. Chegou a um ponto em que a história termina primeiro ou eu morro antes que isso aconteça. Mas pretendo terminar. Embora você possa dizer isso em um ponto da história – onde Gon conhece Ging – completei a história uma vez. […] Como leitor da Jump, também me lembro de ter pensado ‘‘esse mangá não deveria ter acabado aqui?’ e me sentindo puto quando continuava. Quero estar sempre em contato com esse sentimento como leitor”. Em outras palavras, ele pretende terminar Hunter x Hunter antes de morrer, mas talvez todos possamos esperar que ele tenha uma vida-longa e feliz, independentemente de sua produção criativa, ou seja, vai demorar.',
'1000'
);

INSERT INTO tbartigo (subTitulo1,p1,subTitulo2,p2,fkPublicacao) VALUES 
(
'John Wick 3 - Parabellum',
'Quando o primeiro filme de John Wick (Keanu Reeves) chegou aos cinemas, em 2014, não sabíamos nada sobre o personagem. Sua aparência bastante pacata escondia um dos melhores assassinos de aluguel que fez parte de uma liga de matadores profissionais treinados em todos os tipos de armas, lutas e o que mais for preciso para completar uma missão. Tudo o que Wick gostaria naquele momento era passar o resto de seus dias em casa, lembrando dos momentos felizes que viveu ao lado de sua finada mulher e curtindo a companhia do seu cachorro. Dizer que o passado bateu à sua porta seria um desrespeito à memória da porta, que literalmente virou pó no segundo capítulo, de 2017. Se você não viu os dois filmes, este resumo é tudo o que você precisa saber e é mais do que vão te dar, pois quando o terceiro capítulo começa, John e seu cachorro estão se arrastando por Nova York, numa sequência imediata ao que aconteceu no anterior, quando ele acaba matando uma pessoa dentro do Hotel Continental (zona neutra dentro da etiqueta dos assassinos) e agora tem um prêmio de 14 milhões para quem entregá-lo. ',
'Vale a pena?',
'Mesmo que a história seja "apenas um detalhe” no meio de tantos corpos caindo no chão, John Wick 3: Parabellum convoca Angelica Houston e Hale Berry para nos levarem a degraus mais altos e profundos da Mesa Alta. As cenas de ação no Marrocos ao lado de Berry envolvem dois cachorros e, obviamente, muitos tiros, mas as grandes novidades do filme vêm mais do leste. Se lambuzando descaradamente do cinema asiático, o filme traz ninjas para suas sombras e pega emprestado ainda batalhas com katanás em cima de motos e muitas lutas envolvendo artes-marciais. Os fãs de Western vão vibrar com o momento bangue-bangue em uma loja de antiguidades e com a fuga em cima de um cavalo (depois de uma luta em um estábulo). Com sua cabeça a prêmio, John Wick vai ter que usar tudo o que tem para se manter vivo. Continuamos sem saber tudo sobre ele, mas cresce a certeza de que ele é uma espécie de Superman sem superpoderes, um Jack Bauer que passa mais do que apenas 24 horas sofrendo, um Ethan Hunt mais caseiro e urbano sem reviravoltas ou um James Bond sem gadgets - e que você não deve mexer no cachorro ou no carro dele.',
'1001'
);

INSERT INTO tbartigo (subTitulo1,p1,subTitulo2,p2,fkPublicacao) VALUES 
(
'Entenda a polêmica ao redor do filme',
'Coringa chega aos cinemas em meio a um clima divisivo. Embora seja considerado um grande candidato ao Oscar 2020, o longa se vê também envolvido em uma polêmica diretamente associada à dura realidade dos massacres com armas de fogo nos Estados Unidos. Desde sua primeira exibição, a história da transformação de Arthur Fleck no icônico vilão da DC foi alvo de críticas por possivelmente incitar atos de violência. Afinal, há quem veja na revolução criada pelo personagem de Joaquin Phoenix na trama um potencial apoio a atos criminosos que já acontecem com frequência no mundo real. Para que você fique por dentro do caso, relembre a seguir toda a controvérsia: A ESTREIA EM VENEZA Coringa/Warner Bros/Divulgação O diretor Todd Phillips exibiu Coringa pela primeira vez durante o Festival de Veneza, onde a reação imediata do público foram oito minutos de palmas. A aclamação foi confirmada dias depois, quando o filme levou o prêmio máximo do evento, o Leão de Ouro. Porém, ainda que tudo parecesse indicar o sucesso da nova produção da DC, nem todos os críticos viram com bons olhos a nova história de origem',
'Vale a pena?',
'Diante das críticas negativas e do burburinho nas redes sociais, o diretor Todd Phillips pediu que o público desse uma chance à produção e tirasse suas próprias conclusões. "O filme trata da falta de amor, trauma da infância e falta de compaixão no mundo. Acredito que as pessoas conseguem aguentar essa mensagem", afirmou ao IGN. "Para mim, a arte pode ser complicada e, às vezes, a arte é feita para ser complicada. Se você quer arte descomplicada, talvez você deva ter aulas de caligrafia, mas fazer cinema é sempre uma arte complicada". Dias depois, Phillips voltou a comentar a polêmica, dessa vez levando em consideração à carta aberta dos familiares das vítimas do ataque de 2012. “O que aconteceu em Aurora é obviamente uma situação horrível, mas mesmo aquilo não foi culpa do filme. Francamente, você pode fazer sua própria pesquisa sobre Aurora, que o cavalheiro não estava nem vestido como Coringa, isso foi um engano. Seu cabelo estava pintado de vermelho e ele estava obviamente em meio a um colapso mental e foi algo terrível, mas não há relação a não ser ter acontecido em um cinema”, afirmou à Associated Press. Já sobre a violência explícita em Coringa, o diretor questionou por que ela não é tratada como um problema também em filmes como John Wick.',
'1002'
);

INSERT INTO tbartigo (subTitulo1,p1,subTitulo2,p2,fkPublicacao) VALUES 
(
'Não há realmente ponto negativo na obra',
'Vencedor do Urso de Ouro do Festival de Cinema de Berlim e do Oscar 2003 de melhor longa-metragem de animação, A viagem de Chihiro (Sen to Chihiro no kamikakushi, 2001), de autoria de Hayao Miyazaki - o maior animador do Japão - é, sem exagero, um dos melhores desenhos animados de todos os tempos. O filme começa com Chihiro, uma menina mimada e medrosa, viajando com seus pais para uma casa nova. A família pega o caminho errado e vai parar na entrada de um misterioso túnel. Eles decidem, então, ver o que há no final da passagem e encontram... Bom, não vou estragar as surpresas (que são muitas), mas Chihiro tem que salvar seus pais e aprender a superar seus medos e limitações em uma história que pode ser classificada como um conto de fadas moderno. A trama é espetacular e, diferente da produção anterior de Miyazaki (Princesa Mononoke, inédita no Brasil), completamente livre de violência e recomendada tanto para crianças quanto para adultos. Há situações bastante esdrúxulas, que, somadas ao inexplicável discurso anti-animação que Miyazaki fez ao receber o Urso de Ouro, levam-nos a duvidar da sanidade do bom velhinho - embora nunca de seu talento e genialidade. Em todo caso, a narrativa é magnífica e justifica, por si só, o prestigioso prêmio.',
'Vale a pena?',
'A viagem de Chihiro também retoma muitos dos antigos conceitos de seu autor, utilizando elementos de Mononoke, Porco Rosso e Meu Amigo Totoro (estes últimos lançados no Brasil em VHS pela Flashstar) para produzir uma espécie de afirmação definitiva de Miyazaki na animação. Aliás, na época do lançamento do filme, o diretor tencionava que este fosse o último de sua carreira. Contudo, já está trabalhando em Howls moving castle e revelou que fará uma animação totalmente em computação gráfica ao lado do Pixar Animation Studios (leia aqui). Merece destaque também a trilha sonora do filme, criada pelo compositor habitual dos filmes do Ghibli, Joe Hisaishi, que mostra a competência de sempre, complementando as imagens com perfeição. Enfim, não há realmente ponto negativo na obra. Alguns adultos mais cínicos podem achá-lo um tanto infantil (não é!) e crianças mais sensíveis podem se assustar com certas seqüências, mas nada demais se comparado à morte da mãe do Bambi... Esta é uma animação que o Omelete recomenda enfaticamente. Não deixe de assistir. E leve a família!',
'1003'
);

INSERT INTO tbartigo (subTitulo1,p1,subTitulo2,p2,fkPublicacao) VALUES 
(
'Como a série mudou a televisão para sempre',
'Há mais de dez anos Breaking Bad estreava seu primeiro episódio. A série, que não contava com nenhuma grande estrela do cinema ou tinha um nome conhecido em seus bastidores, começou discreta e ao final da segunda parte de sua quinta temporada tornou-se um fenômeno cultural que transformou para sempre a televisão. Com um roteiro cirúrgico, uma fotografia inovadora e atuações marcantes, rapidamente ela virou o marco da nova era de ouro da televisão. A série foi a primeira a se aproveitar do fenômeno Netflix. Apesar de ser amplamente elogiada pela crítica ao longo de suas primeiras temporadas, o drama não era um sucesso de público. A média de audiência era relativamente baixa, entre 1,2 e 1,9 milhão de espectadores (para base de comparação, a temporada de Big Bang Theory com audiência mais baixa contou com 8,3 milhões de espectadores). Contudo, tudo mudou quando a série ficou disponível no serviço de streaming. Com a oportunidade dos fãs de maratonar, o seriado cresceu ano após ano e virou um fenômeno justamente quando estava prestes a acabar. Com esse crescimento, os produtores decidiram dividir a quinta temporada em duas partes – com oito episódios lançados em 2012 e mais oito estreando em 2013. Foi nesse momento que ficou claro o crescimento do seriado após sua entrada na Netflix: o encerramento da quarta temporada contou com 1,9 milhão de espectadores, enquanto o final da série teve 10,2 milhões de pessoas. “Acredito que a Netflix nos manteve no ar”, admitiu Vince Gilligan, criador do programa, no Emmy de 2013 (via Mashbale).',
'Vale a pena?',
'Jesse era o contraponto perfeito de Walter White. Enquanto o garoto admitia ser um vilão (mas no fundo não era), o novo Rei das Drogas nunca olhava para si como um homem mal (quando na verdade estava cada vez pior). Jesse é um dos personagens mais importantes da série e sua relação com Walt fortaleceu o personagem e sua jornada. “Lembro que a guia de Vince para Walt sempre foi mostrar a transformação do Mr. Chipps [o professor simpático do filme Adeus, Mr. Chips] no Scarface [personagem imortalizado por Al Pacino]”, afirmou Bryan Cranston ao THR em 2011. Gilligan pode ter mudado o destino de alguns personagens, mas nunca abandonou essa ideia de mostrar a transformação de um homem comum em um vilão. O elenco, que foi muito bem escalado, conseguiu mudar junto com seus papeis e foram guiados pela performance histórica de Cranston. O ator é o ponto alto da série. Conhecido por comédias como Malcom in the Middle, ele se transformou completamente para viver aquele que considera o papel de sua vida. Em nenhum momento ele julga as ações de seu personagem e entrega uma performance viva, realista e humana. “Você vê humanidade nele, mesmo quando ele faz as coisas mais terríveis, mesmo quando toma as piores decisões. Você precisa de alguém que tenha humanidade para que o espectador diga ‘muito bem, eu compro essa ideia. Não gosto do que ele está fazendo, mas eu entendo, e vou ver onde vai chegar’. Se você não tem um cara que te dá isso, o programa não vai para frente”, afirmou Gilligan em 2009 ao NJ.com. Breaking Bad ajudou a revolucionar a televisão. Hoje, atores e atrizes de renome estão voltando seus olhos para séries que, cada vez mais, são o melhor lugar para criar projetos arriscados e diferentes. Breaking Bad ajudou a pavimentar esse caminho e, por isso, é uma das séries mais importantes da história.',
'1004'
);